# Michelson Interferometer Control Software
# https://github.com/gucci-on-fleek/michelson-interferometer
# SPDX-License-Identifier: MPL-2.0+
# SPDX-FileCopyrightText: 2026 Max Chernoff

################
### Metadata ###
################

[project]
# Basic metadata.
name = "michelson-interferometer"
license = "MPL-2.0+"
authors = [{ name = "Max Chernoff" }]
readme = "README.md"

# Project version.
version = "1.0.0" # %%version

# Don't upload to PyPI.
classifiers = ["Private :: Do Not Upload"]

# The main entry point for the GUI.
scripts.michelson-interferometer = "michelson_interferometer:gui.main"


####################
### Dependencies ###
####################

# The same version that's in the Gnome Flatpak runtime.
requires-python = "~= 3.12"

dependencies = [
    # We use Matplotlib to plot the measured data.
    "matplotlib ~= 3.10",

    # We use PyLabLib to interface with both the motor and detector hardware.
    "pylablib-lightweight[devio, extra] ~= 1.4",

    # Polars is a modern version of Pandas which we use to save and manipulate
    # our measured data.
    "polars ~= 1.34",

    # Newer versions of SciPy (https://github.com/scipy/scipy/commit/a06de4e129)
    # replace the C implementation of the Lomb--Scargle periodogram with a
    # Python implementation, which is significantly slower and uses
    # substantially more memory. Therefore, we need to pin SciPy to an older
    # version.
    "scipy < 1.15",
]

[project.optional-dependencies]
gtk = [
    # We use PyGObject to draw the GUI (using GTK4 + Adwaita), and we pin it to
    # the exact version that's installed in the Gnome Flatpak runtime.
    "PyGObject == 3.52.3",

    # Also pin PyCairo to the version in the Gnome Flatpak runtime.
    "pycairo == 1.28.0",
]
dev = [
    # We use a Makefile to manage the build process, so use setuptools to
    # generate the wheel. Once again, we pin this to the exact version of
    # setuptools that's installed in the Gnome Flatpak SDK.
    "setuptools == 83.0.0",

    # Provides the type stubs for PyGObject.
    "pygobject-stubs ~= 2.13.0",
]


######################
### Build Settings ###
######################

[build-system]
# Should be identical to the "dev" group above.
requires = ["setuptools == 83.0.0", "pygobject-stubs ~= 2.13.0"]

# Use setuptools to build the project.
build-backend = "setuptools.build_meta"

# Tell setuptools how to find our package.
[tool.setuptools.packages.find]
where = ["."]
include = ["michelson_interferometer"]
namespaces = false

# Include the UI files in the package, since they're needed to run the GUI.
[tool.setuptools.package-data]
michelson_interferometer = ["*.ui"]

[tool.uv]
# This package only supports Linux due to the hardware interfacing code, and
# I've only ever tested it on x86_64, so restrict to a single platform to reduce
# the lockfile. size.
environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]

# Wait for 1 week before installing package updates to avoid supply-chain
# attacks.
exclude-newer = "7 days"

# Only use binary packages (wheels); this ensures that no untrusted code is run.
# during installation.
no-build = true

# Well, we need to build ourself from source---that's the entire point of this.
no-binary-package = ["michelson-interferometer"]


##############################
### Formatting and Linting ###
##############################

[tool.ruff]
# Shorter line lengths are more readable.
line-length = 80

# Automatically fix formatting and linting issues.
fix = true

# Enable experimental features.
preview = true

[tool.ruff.lint]

# Add the following lint rule categories to the default set.
extend-select = [
    "ANN", # flake8-annotations
    "ASYNC", # flake8-async
    "D", # pydocstyle
    "DOC", # pydoclint
    "I", # isort
    "ISC", # flake8-implicit-str-concat
    "NPY", # numpy
    "PL", # pylint
    "PT", # flake8-pytest-style
    "PTH", # flake8-use-pathlib
    "UP", # pyupgrade
]

# Ignore the following rules.
extend-ignore = [
    "any-type",
    "blank-line-after-function",
    "cached-instance-method",
    "docstring-missing-exception",
    "docstring-missing-returns",
    "import-outside-top-level",
    "missing-type-args",
    "missing-type-kwargs",
    "too-many-branches",
    "try-except-pass",
    "undefined-name",
    "undocumented-magic-method",
]

# `pprint` is useful to have for debugging, allow it to be imported without
# triggering a lint error, even if it's not used in the code.
pyflakes.allowed-unused-imports = ["pprint"]

[tool.ruff.lint.isort]
# Put 2 blank lines after imports.
lines-after-imports = 2

# Combine all imports from the same module into a single line.
combine-as-imports = true
split-on-trailing-comma = false

# Group GTK imports into a separate section
sections.gtk = ["gi"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
    "gtk",
]


#####################
### Type Checking ###
#####################

[tool.pyright]
# Make the Pyright type checker stricter.
typeCheckingMode = "strict"
deprecateTypingAliases = true
reportUnnecessaryTypeIgnoreComment = true

# But not _too_ strict.
reportUnusedImport = "hint"
reportPrivateUsage = "hint"
reportMissingTypeStubs = "hint"
reportUnknownMemberType = "hint"
reportUnknownLambdaType = "hint"
